dnsdist: Work around empty DNSName in the q/a in-memory ringbuffer
It should not be there in the first place, but with this fix at
least we can display the remaining entries, instead of getting:

Error: Exception thrown by a callback function called by Lua:
empty dnsnames aren't part of anything